services:
  - type: web
    name: evsu-fleet-tracker
    env: python
    region: singapore
    plan: free
    buildCommand: >
      pip install -r requirements.txt
    releaseCommand: >
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: RENDER
        value: 'true'
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: 'evsu-fleet-tracker.onrender.com'
      - key: DATABASE_URL
        fromDatabase:
          name: evsu-fleet-tracker-db
          property: connectionString
