# Generated by Django 6.0.5 on 2026-06-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_type_asset_asset_type_asset_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
