# Generated by Django 6.0.5 on 2026-06-03 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='procurement_cost',
        ),
        migrations.AddField(
            model_name='asset',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('VEHICLE', 'Vehicle'), ('IT', 'IT Equipment'), ('OFFICE', 'Office Equipment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50),
        ),
    ]
