# Generated by Django 6.0.5 on 2026-06-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='added_by',
        ),
    ]
