# Generated by Django 6.0.5 on 2026-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('AUDITOR', 'Auditor'), ('MANAGER', 'Manager'), ('DRIVER', 'Driver')], default='STAFF', max_length=20),
        ),
    ]
