# Generated by Django 6.0.5 on 2026-06-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('IT', 'IT Equipment'), ('OFFICE', 'Office Equipment'), ('VEHICLE', 'Vehicle'), ('FURNITURE', 'Furniture')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
    ]
