# Generated by Django 6.0.5 on 2026-06-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='qr_code',
        ),
    ]
