# Generated by Django 6.0.5 on 2026-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_asset_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user account was created', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('FLEET_MANAGER', 'Fleet Manager'), ('STAFF', 'Staff')], default='STAFF', help_text='User role for access control', max_length=20),
        ),
    ]
