# Generated by Django 6.0.5 on 2026-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100)),
                ('requested_by', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
