# Generated by Django 6.0.5 on 2026-06-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_audittrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='asset_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
